[build]
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  GIST_ID = "09ad334f546c906896ec7b93621ae643"
  GIST_TOKEN = "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"
